# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, cabalInstall, aeson, HTTP, text, twitterConduit, lens }:

cabal.mkDerivation (self: {
  pname = "twitter-world-leaders";
  version = "0.1.0.0";
  src = ./.;
  isLibrary = false;
  isExecutable = true;
  buildTools = [ cabalInstall ];
  buildDepends = [ aeson HTTP text twitterConduit lens ];
  meta = {
    platforms = self.ghc.meta.platforms;
  };
})
